const words = [
    {
        "id":"13992",
        "english":"blood",
        "transcription":"[blʌd]]",
        "russian":"кровь"
    },{
        "id":"13993",
        "english":"bemused",
        "transcription":"[bɪˈmjuːzd]",
        "russian":"ошеломленный"
    },{
        "id":"13994",
        "english":"book",
        "transcription":"[bʊk]",
        "russian":"книга"
    },{
        "id":"13995",
        "english":"beauty",
        "transcription":"[ˈbjuːtɪ]",
        "russian":"красота"
    },{
        "id":"13996",
        "english":"shotgun",
        "transcription":"[ˈʃɒtgʌn]",
        "russian":"бессистемный"
    },{
        "id":"13997",
        "english":"wood",
        "transcription":"[wʊd]",
        "russian":"дерево"
    },{
        "id":"13998",
        "english":"castle",
        "transcription":"[kɑːsl]",
        "russian":"замок"
    },{
        "id":"13999",
        "english":"faithful",
        "transcription":"[ˈfeɪθf(ə)l]",
        "russian":"верный"
    },{
        "id":"14000",
        "english":"pain",
        "transcription":"[peɪn]",
        "russian":"боль",
        "tags":"fog_prince"
    },{
        "id":"14001",
        "english":"bride",
        "transcription":"[braɪd]",
        "russian":"невеста"
    },{
        "id":"14002",
        "english":"ability",
        "transcription":"[əˈbɪləti]",
        "russian":"умение, способность"
    },{
        "id":"14010",
        "english":"necessity",
        "transcription":"[nɪˈsesɪtɪ]",
        "russian":"необходимость"
    },{
        "id":"14011",
        "english":"perform",
        "transcription":"[pəˈfɔːm]",
        "russian":"выполнять"
    },{
        "id":"14012",
        "english":"spell",
        "transcription":"[ðiː spel]",
        "russian":"заклинание"
    },{
        "id":"14013",
        "english":"cat",
        "transcription":"[kæt]",
        "russian":"кошка"
    },{
        "id":"14014",
        "english":"dog",
        "transcription":"[dɒg]",
        "russian":"собака"
    },{
        "id":"14015",
        "english":"apple",
        "transcription":"[æpl]",
        "russian":"яблоко"
    },{
        "id":"14016",
        "english":"orange",
        "transcription":"[ˈɒrɪnʤ]",
        "russian":"апельсин"
    },{
        "id":"14017",
        "english":"mountain",
        "transcription":"[ˈmaʊntɪn]",
        "russian":"гора"
    },{
        "id":"14020",
        "english":"water",
        "transcription":"[ˈwɔːtə]",
        "russian":"вода"
    },{
        "id":"14021",
        "english":"fire",
        "transcription":"[ˈfaɪə]",
        "russian":"огонь"
    },{
        "id":"14022",
        "english":"air",
        "transcription":"[eə]",
        "russian":"воздух"
    },{
        "id":"14023",
        "english":"earth",
        "transcription":"[ɜːθ]",
        "russian":"земля"
    },{
        "id":"14043",
        "english":"running",
        "transcription":"[ˈrʌnɪŋ]",
        "russian":"бег","tags":"существительное"
    },{
        "id":"14044",
        "english":"sing",
        "transcription":"[sɪŋ]",
        "russian":"петь"
    },{
        "id":"14046",
        "english":"play",
        "transcription":"[pleɪ]",
        "russian":"играть"
    },{
        "id":"14047",
        "english":"car",
        "transcription":"[kär]",
        "russian":"автомобиль"
    },{
        "id":"14048",
        "english":"sleep",
        "transcription":"[sliːp]",
        "russian":"спать"
    },{
        "id":"14062",
        "english":"wolf",
        "transcription":"[ wulf ]",
        "russian":"волк"
    },{
        "id":"14067",
        "english":"frog",
        "transcription":"[ frɔg ]",
        "russian":"лягушка"
    },{
        "id":"14070",
        "english":"sand",
        "transcription":"[ sænd ]",
        "russian":"песок"
    },{
        "id":"14071",
        "english":"crab",
        "transcription":"[ kræb ]",
        "russian":"краб"
    },{
        "id":"14072",
        "english":"green",
        "transcription":"[ gri:n ]",
        "russian":"зеленый"
    },{
        "id":"14073",
        "english":"lion",
        "transcription":"[leon]",
        "russian":"лев"
    },{
        "id":"14074",
        "english":"bee",
        "transcription":"[ bi: ]",
        "russian":"пчела"
    },{
        "id":"14075",
        "english":"bear",
        "transcription":"[ bɛə ]",
        "russian":"медведь"
    }
]
export default words;